import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import {
  BaseEdge,
  EdgeLabelRenderer,
  MarkerType,
  Position,
  type EdgeProps,
  useReactFlow,
  useStore,
} from '@xyflow/react'
import { getPolylineLabelAnchors } from './edgeLabels/edgeLabelPosition'
import { SmartEdgeLabel } from './edgeLabels/SmartEdgeLabel'
import type { EdgeLabelLayoutConfig, EdgeLabelStyle } from './edgeLabels/types'
import { QuickTextStyleToolbar, QUICK_TOOLBAR_DATA_ATTR } from './QuickTextStyleToolbar'
import { padEdgeEndpoints } from './edgeEndpointPad'
import { getNodeExclusionBoxes } from './layout/routing/exclusion'
import { orthogonalizePolyline, resolveOrthogonalPathAvoidingObstacles } from './layout/routing/orthogonalObstacleDetour'
import { GRID_UNIT, SIZE_STEP_RATIO, normalizeWaypointsToGrid, snapPointToGrid, snapToGrid } from './grid'

type SwimlaneEdgeSemanticType = 'normal' | 'crossLane' | 'returnFlow' | 'conditional'

type EdgeData = {
  waypoints?: Point[]
  layoutProfile?: string
  autoGeneratedSwimlane?: boolean
  routeRef?: {
    sourceX: number
    sourceY: number
    targetX: number
    targetY: number
  }
  editingLabel?: boolean
  labelStyle?: EdgeLabelStyle
  labelLayout?: EdgeLabelLayoutConfig
  arrowStyle?: 'none' | 'end' | 'start' | 'both'
  semanticType?: SwimlaneEdgeSemanticType
  sourceLaneId?: string
  targetLaneId?: string
  labelTextOnly?: boolean
  labelSettingsUnlocked?: boolean
}
type Point = { x: number; y: number }
const ORTHO_EPS = 1e-6
const EDGE_STEP_UNIT = Math.max(1, GRID_UNIT * SIZE_STEP_RATIO)
type NormalizeAnchor = 'source' | 'target'

function markerColorFrom(style: EdgeProps['style'], marker: unknown): string {
  const mk = (marker ?? {}) as { color?: string }
  const s = (style ?? {}) as { stroke?: string; ['--xy-edge-stroke']?: string }
  return s['--xy-edge-stroke'] ?? s.stroke ?? mk.color ?? '#94a3b8'
}

function markerKindFrom(marker: unknown): 'closed' | 'open' | null {
  if (!marker || typeof marker !== 'object') return null
  const t = (marker as { type?: unknown }).type
  if (t === MarkerType.ArrowClosed || t === 'arrowclosed') return 'closed'
  if (t === MarkerType.Arrow || t === 'arrow') return 'open'
  return null
}

/**
 * 生成圆角正交折线路径（几何上保持 90 度拐弯方向）
 */
function createRoundedPath(points: Point[], radius: number): string {
  if (points.length < 2) return ''

  let path = `M ${points[0].x} ${points[0].y}`

  for (let i = 1; i < points.length - 1; i++) {
    const prev = points[i - 1]
    const curr = points[i]
    const next = points[i + 1]

    const dx1 = curr.x - prev.x
    const dy1 = curr.y - prev.y
    const dx2 = next.x - curr.x
    const dy2 = next.y - curr.y

    const len1 = Math.sqrt(dx1 * dx1 + dy1 * dy1)
    const len2 = Math.sqrt(dx2 * dx2 + dy2 * dy2)

    if (len1 === 0 || len2 === 0) {
      path += ` L ${curr.x} ${curr.y}`
      continue
    }

    const r = Math.min(radius, len1 / 2, len2 / 2)

    const startX = curr.x - (dx1 / len1) * r
    const startY = curr.y - (dy1 / len1) * r
    const endX = curr.x + (dx2 / len2) * r
    const endY = curr.y + (dy2 / len2) * r

    path += ` L ${startX} ${startY}`
    path += ` Q ${curr.x} ${curr.y} ${endX} ${endY}`
  }

  path += ` L ${points[points.length - 1].x} ${points[points.length - 1].y}`

  return path
}

/**
 * 计算每个线段的信息，用于渲染拖拽手柄
 */
function getSegments(points: Point[]): Array<{
  index: number
  x1: number
  y1: number
  x2: number
  y2: number
  midX: number
  midY: number
  isVertical: boolean
  length: number
}> {
  const segments: Array<{
    index: number
    x1: number
    y1: number
    x2: number
    y2: number
    midX: number
    midY: number
    isVertical: boolean
    length: number
  }> = []
  
  for (let i = 0; i < points.length - 1; i++) {
    const p1 = points[i]
    const p2 = points[i + 1]
    const dx = Math.abs(p2.x - p1.x)
    const dy = Math.abs(p2.y - p1.y)
    const isVertical = dx < dy // 垂直段: dy 更大
    
    segments.push({
      index: i,
      x1: p1.x,
      y1: p1.y,
      x2: p2.x,
      y2: p2.y,
      midX: (p1.x + p2.x) / 2,
      midY: (p1.y + p2.y) / 2,
      isVertical,
      length: Math.sqrt(dx * dx + dy * dy),
    })
  }
  
  return segments
}

function hasDiagonalSegment(points: Point[]): boolean {
  for (let i = 0; i < points.length - 1; i += 1) {
    const a = points[i]
    const b = points[i + 1]
    const dx = Math.abs(b.x - a.x)
    const dy = Math.abs(b.y - a.y)
    if (dx > ORTHO_EPS && dy > ORTHO_EPS) return true
  }
  return false
}

function coerceRenderablePath(
  source: Point,
  target: Point,
  rawWaypoints: Point[],
  sourcePosition: Position,
  targetPosition: Position,
): Point[] {
  const candidate = [source, ...rawWaypoints, target]
  const orthogonalized = orthogonalizePolyline(candidate)
  const endpointSnapped = snapEndpointsToPorts(orthogonalized, sourcePosition, targetPosition)
  const normalizedWaypoints = normalizeWaypointsToGrid(endpointSnapped.slice(1, -1), EDGE_STEP_UNIT)
  const rebuilt = [source, ...normalizedWaypoints, target]
  if (!hasDiagonalSegment(rebuilt)) return rebuilt

  const repaired = snapEndpointsToPorts(orthogonalizePolyline(rebuilt), sourcePosition, targetPosition)
  const repairedWaypoints = normalizeWaypointsToGrid(repaired.slice(1, -1), EDGE_STEP_UNIT)
  return [source, ...repairedWaypoints, target]
}

/** 让首尾两段与端口方向对齐，避免 in/out 出现斜线 */
function snapEndpointsToPorts(
  points: Point[],
  sourcePosition: Position,
  targetPosition: Position,
): Point[] {
  if (points.length < 3) return points

  const snapped = points.map((p) => ({ ...p }))

  // L-case with a single middle point can get folded into a diagonal when we
  // enforce both source-out and target-in on the same point. Split it first.
  if (snapped.length === 3) {
    const src = snapped[0]
    const mid = snapped[1]
    const tgt = snapped[2]
    const sourceHorizontal = sourcePosition === Position.Left || sourcePosition === Position.Right
    const targetHorizontal = targetPosition === Position.Left || targetPosition === Position.Right
    const first = sourceHorizontal ? { x: mid.x, y: src.y } : { x: src.x, y: mid.y }
    const last = targetHorizontal ? { x: mid.x, y: tgt.y } : { x: tgt.x, y: mid.y }
    snapped.splice(1, 1, first, last)
  }

  // Keep a minimal terminal lead on both ends while dragging, so the edge
  // does not visually fold back into the node.
  // Allow lead=0 so users can merge the in/out-parallel segment into one straight line.
  // We still keep direction constraints (no reverse fold), but no forced minimum bend distance.
  const MIN_TERMINAL_LEAD = 0

  // 第一段：源节点 → 第一个中间点
  const src = snapped[0]
  const first = snapped[1]
  if (sourcePosition === Position.Left || sourcePosition === Position.Right) {
    // 水平出发：和源节点保持同一条水平线
    first.y = src.y
    // 保证「out」方向一定朝节点外侧（Right: 从左往右出；Left: 从右往左出）
    if (sourcePosition === Position.Left) first.x = Math.min(first.x, src.x - MIN_TERMINAL_LEAD)
    if (sourcePosition === Position.Right) first.x = Math.max(first.x, src.x + MIN_TERMINAL_LEAD)
    // 保证第一拐点后续仍为垂直：第二段应与 first 的 x 对齐
    const next = snapped[2]
    if (next) next.x = first.x
  } else {
    // 垂直出发：和源节点保持同一条竖线
    first.x = src.x
    // 保证「out」方向一定朝节点外侧（Bottom: 从上往下出；Top: 从下往上出）
    if (sourcePosition === Position.Top) first.y = Math.min(first.y, src.y - MIN_TERMINAL_LEAD)
    if (sourcePosition === Position.Bottom) first.y = Math.max(first.y, src.y + MIN_TERMINAL_LEAD)
    // 保证第一拐点后续仍为水平：第二段应与 first 的 y 对齐
    const next = snapped[2]
    if (next) next.y = first.y
  }

  // 最后一段：最后一个中间点 → 目标节点
  const tgt = snapped[snapped.length - 1]
  const lastIdx = snapped.length - 2
  const last = snapped[lastIdx]
  if (targetPosition === Position.Left || targetPosition === Position.Right) {
    // 水平进入：和目标节点保持同一条水平线
    last.y = tgt.y
    // 保证「in」方向一定朝节点内侧（Right: 从右往左进入；Left: 从左往右进入）
    if (targetPosition === Position.Left) last.x = Math.min(last.x, tgt.x - MIN_TERMINAL_LEAD)
    if (targetPosition === Position.Right) last.x = Math.max(last.x, tgt.x + MIN_TERMINAL_LEAD)
    // 保证最后一个拐点前后仍为正交：倒数第二段需与 last 的 x 对齐
    const prev = snapped[lastIdx - 1]
    if (prev) prev.x = last.x
  } else {
    // 垂直进入：和目标节点保持同一条竖线
    last.x = tgt.x
    // 保证「in」方向一定朝节点内侧（Bottom: 从下往上进入；Top: 从上往下进入）
    if (targetPosition === Position.Top) last.y = Math.min(last.y, tgt.y - MIN_TERMINAL_LEAD)
    if (targetPosition === Position.Bottom) last.y = Math.max(last.y, tgt.y + MIN_TERMINAL_LEAD)
    // 保证最后一个拐点前后仍为正交：倒数第二段需与 last 的 y 对齐
    const prev = snapped[lastIdx - 1]
    if (prev) prev.y = last.y
  }

  return snapped
}

function normalizeOrthogonalWaypoints(
  source: Point,
  target: Point,
  waypoints: Point[],
  sourcePosition: Position,
  targetPosition: Position,
  opts?: { anchor?: NormalizeAnchor },
): Point[] {
  if (waypoints.length === 0) return []
  const full = [source, ...waypoints.map((p) => snapPointToGrid({ ...p }, EDGE_STEP_UNIT)), target]
  const anchor = opts?.anchor ?? 'source'

  if (anchor === 'target') {
    let horizontal = targetPosition === Position.Left || targetPosition === Position.Right
    for (let i = full.length - 2; i >= 1; i -= 1) {
      if (horizontal) {
        full[i].y = full[i + 1].y
      } else {
        full[i].x = full[i + 1].x
      }
      horizontal = !horizontal
    }
  } else {
    let horizontal = sourcePosition === Position.Left || sourcePosition === Position.Right
    for (let i = 1; i < full.length - 1; i += 1) {
      if (horizontal) {
        full[i].y = full[i - 1].y
      } else {
        full[i].x = full[i - 1].x
      }
      horizontal = !horizontal
    }
  }

  const targetHorizontal = targetPosition === Position.Left || targetPosition === Position.Right
  const lastIdx = full.length - 2
  if (lastIdx >= 1) {
    if (targetHorizontal) {
      full[lastIdx].y = full[full.length - 1].y
    } else {
      full[lastIdx].x = full[full.length - 1].x
    }
  }

  const snapped = snapEndpointsToPorts(full, sourcePosition, targetPosition)
  const snappedWaypoints = normalizeWaypointsToGrid(snapped.slice(1, -1), EDGE_STEP_UNIT)
  const refined = snapEndpointsToPorts([source, ...snappedWaypoints, target], sourcePosition, targetPosition)
  const orthogonalized = orthogonalizePolyline(refined)
  const endpointSnapped = snapEndpointsToPorts(orthogonalized, sourcePosition, targetPosition)
  return normalizeWaypointsToGrid(endpointSnapped.slice(1, -1), EDGE_STEP_UNIT)
}

/**
 * 拖拽并线时的意图识别：
 * - 若拖拽线段与 in/out 末段平行，比较它到 source(out) 与 target(in) 的距离；
 * - 更接近 in 则以 target 端为锚归一化（并到 in）；
 * - 更接近 out 则以 source 端为锚归一化（并到 out）。
 */
export function resolveDragNormalizeAnchorPreference(args: {
  movedPoints: Point[]
  segIndex: number
  isVertical: boolean
  source: Point
  target: Point
  sourcePosition: Position
  targetPosition: Position
}): NormalizeAnchor | undefined {
  const {
    movedPoints,
    segIndex,
    isVertical,
    source,
    target,
    sourcePosition,
    targetPosition,
  } = args
  if (movedPoints.length < 3) return undefined
  if (segIndex < 0 || segIndex + 1 >= movedPoints.length) return undefined

  const sourceTerminalVertical = !(sourcePosition === Position.Left || sourcePosition === Position.Right)
  const targetTerminalVertical = !(targetPosition === Position.Left || targetPosition === Position.Right)
  const sourceParallel = sourceTerminalVertical === isVertical
  const targetParallel = targetTerminalVertical === isVertical
  // 泳道图生成边常见“仅一端平行”的场景：
  // - 若仅与 in 端平行，优先并到 in；
  // - 若仅与 out 端平行，优先并到 out。
  if (!sourceParallel && !targetParallel) return undefined
  if (!sourceParallel && targetParallel) return 'target'
  if (sourceParallel && !targetParallel) return 'source'

  const p1 = movedPoints[segIndex]
  const p2 = movedPoints[segIndex + 1]
  const movedCoord = isVertical ? (p1.x + p2.x) / 2 : (p1.y + p2.y) / 2
  const sourceCoord = isVertical ? source.x : source.y
  const targetCoord = isVertical ? target.x : target.y
  const dOut = Math.abs(movedCoord - sourceCoord)
  const dIn = Math.abs(movedCoord - targetCoord)

  // 同轴距离无法区分（例如 source/target 在同一 y 或同一 x）时，
  // 再用二维距离与段位次做偏好，避免总是回退到 source(out)。
  if (Math.abs(dIn - dOut) <= EDGE_STEP_UNIT / 2) {
    const midX = (p1.x + p2.x) / 2
    const midY = (p1.y + p2.y) / 2
    const dOut2d = Math.abs(midX - source.x) + Math.abs(midY - source.y)
    const dIn2d = Math.abs(midX - target.x) + Math.abs(midY - target.y)
    if (Math.abs(dIn2d - dOut2d) > EDGE_STEP_UNIT / 2) {
      return dIn2d < dOut2d ? 'target' : 'source'
    }

    const segmentCount = movedPoints.length - 1
    const distToSource = segIndex
    const distToTarget = segmentCount - 1 - segIndex
    if (distToTarget !== distToSource) return distToTarget < distToSource ? 'target' : 'source'
    return segIndex >= (segmentCount - 1) / 2 ? 'target' : 'source'
  }
  return dIn < dOut ? 'target' : 'source'
}

function adaptWaypointsByRouteRef(
  waypoints: Point[],
  routeRef: EdgeData['routeRef'] | undefined,
  now: { sourceX: number; sourceY: number; targetX: number; targetY: number },
): Point[] {
  if (!routeRef || waypoints.length === 0) return waypoints
  const dsx = now.sourceX - routeRef.sourceX
  const dsy = now.sourceY - routeRef.sourceY
  const dtx = now.targetX - routeRef.targetX
  const dty = now.targetY - routeRef.targetY
  if (Math.abs(dsx) < 1e-6 && Math.abs(dsy) < 1e-6 && Math.abs(dtx) < 1e-6 && Math.abs(dty) < 1e-6) {
    return waypoints
  }
  const n = waypoints.length
  return waypoints.map((p, i) => {
    const t = (i + 1) / (n + 1)
    return {
      x: p.x + dsx * (1 - t) + dtx * t,
      y: p.y + dsy * (1 - t) + dty * t,
    }
  })
}

export function EditableSmoothStepEdge(props: EdgeProps) {
  const {
    id,
    source,
    target,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    markerStart,
    markerEnd,
    style,
    interactionWidth,
    label,
    data,
    selected,
  } = props
  const dataTyped = (data ?? {}) as EdgeData
  const labelStyleObj = (dataTyped.labelStyle ?? (props as { labelStyle?: EdgeLabelStyle }).labelStyle) ?? {}
  const labelFontSize = labelStyleObj.fontSize ?? 10
  const labelFontWeight = labelStyleObj.fontWeight ?? '400'
  const labelColor = labelStyleObj.color ?? 'rgba(0,0,0,0.8)'

  const rf = useReactFlow()

  const obstacleBoxes = useStore((state) => getNodeExclusionBoxes(state.nodes))
  const allEdges = useStore((state) => state.edges as Array<EdgeProps>)
  const allNodes = useStore((state) => state.nodes as Array<any>)

  const srcPos = sourcePosition ?? Position.Right
  const tgtPos = targetPosition ?? Position.Left
  const isMindMapEdge = useMemo(() => {
    if (dataTyped.layoutProfile === 'mind-map') return true
    const srcNode = allNodes.find((n) => String(n.id) === String(source))
    const tgtNode = allNodes.find((n) => String(n.id) === String(target))
    const srcSide = (srcNode?.data as any)?.mindMapSide
    const tgtSide = (tgtNode?.data as any)?.mindMapSide
    return Boolean(srcSide || tgtSide)
  }, [allNodes, dataTyped.layoutProfile, source, target])

  const semanticType = dataTyped.semanticType
  const semanticStyle: React.CSSProperties = {}
  if (semanticType === 'returnFlow') {
    semanticStyle.strokeDasharray = '6 3'
    semanticStyle.opacity = 0.7
  }

  const padded = useMemo(
    () =>
      padEdgeEndpoints({
        sourceX,
        sourceY,
        targetX,
        targetY,
        sourcePosition: srcPos,
        targetPosition: tgtPos,
        // 思维导图强制从 handle 直接出线，不做端点外移。
        pad: isMindMapEdge ? 0 : undefined,
      }),
    [sourceX, sourceY, targetX, targetY, srcPos, tgtPos, isMindMapEdge],
  )

  // 从 data 中获取保存的路径点，或生成默认路径
  const savedWaypoints: Point[] | undefined = dataTyped.waypoints

  const sourcePoint = useMemo(() => ({ x: padded.sourceX, y: padded.sourceY }), [padded.sourceX, padded.sourceY])
  const targetPoint = useMemo(() => ({ x: padded.targetX, y: padded.targetY }), [padded.targetX, padded.targetY])
  const endpointSnapshot = useMemo(
    () => ({
      sourceX: padded.sourceX,
      sourceY: padded.sourceY,
      targetX: padded.targetX,
      targetY: padded.targetY,
    }),
    [padded.sourceX, padded.sourceY, padded.targetX, padded.targetY],
  )
  const effectiveWaypoints = useMemo((): Point[] | undefined => {
    if (!savedWaypoints || savedWaypoints.length === 0) return undefined
    const adapted = adaptWaypointsByRouteRef(savedWaypoints, dataTyped.routeRef, endpointSnapshot)
    return normalizeOrthogonalWaypoints(sourcePoint, targetPoint, adapted, srcPos, tgtPos)
  }, [savedWaypoints, dataTyped.routeRef, endpointSnapshot, sourcePoint, targetPoint, srcPos, tgtPos])

  const points = useMemo((): Point[] => {
    if (effectiveWaypoints && effectiveWaypoints.length > 0) {
      const snappedWaypoints = normalizeOrthogonalWaypoints(
        sourcePoint,
        targetPoint,
        effectiveWaypoints,
        srcPos,
        tgtPos,
      )
      const candidatePoints = coerceRenderablePath(sourcePoint, targetPoint, snappedWaypoints, srcPos, tgtPos)
      // 用户已有 waypoints 时，优先保留手动路径，避免拖拽过程中被自动避障立即“抢回去”。
      return candidatePoints
    }
    const routed = resolveOrthogonalPathAvoidingObstacles({
      sourceX: padded.sourceX,
      sourceY: padded.sourceY,
      targetX: padded.targetX,
      targetY: padded.targetY,
      sourcePosition: srcPos,
      targetPosition: tgtPos,
      offset: 16,
      obstacleBoxes,
      sourceNodeId: String(source),
      targetNodeId: String(target),
      // 仅对“生成泳道图边”放宽强制外廊，避免默认出现不必要 4 弯；
      // 用户手动创建/编辑边不受影响。
      disableExtremeOuterCorridor: Boolean(dataTyped.autoGeneratedSwimlane),
    })
    const routedOrthogonal = orthogonalizePolyline(routed)
    const routedWaypoints = normalizeOrthogonalWaypoints(
      sourcePoint,
      targetPoint,
      routedOrthogonal.slice(1, -1),
      srcPos,
      tgtPos,
    )
    return coerceRenderablePath(sourcePoint, targetPoint, routedWaypoints, srcPos, tgtPos)
  }, [padded, srcPos, tgtPos, effectiveWaypoints, obstacleBoxes, source, target, sourcePoint, targetPoint])

  // 生成圆角路径
  const edgePath = createRoundedPath(points, 12)
  
  // 获取所有线段信息
  const segments = getSegments(points)

  const anchors = useMemo(() => getPolylineLabelAnchors(points), [points])

  const editing = Boolean(dataTyped.editingLabel)
  const [hoveredSegment, setHoveredSegment] = useState<number | null>(null)

  const inputRef = useRef<HTMLTextAreaElement>(null)

  // 编辑时自动全选文本并调整高度
  useEffect(() => {
    if (editing && inputRef.current) {
      inputRef.current.select()
      inputRef.current.style.height = 'auto'
      inputRef.current.style.height = inputRef.current.scrollHeight + 'px'
    }
  }, [editing])

  // 全局文字编辑锁：边文字编辑开启时，压住其它菜单栏
  useEffect(() => {
    window.dispatchEvent(new CustomEvent('flow2go:text-editing', { detail: { active: editing } }))
    return () => {
      window.dispatchEvent(new CustomEvent('flow2go:text-editing', { detail: { active: false } }))
    }
  }, [editing])

  // 兼容历史数据：首次发现 waypoints 且缺 routeRef 时，补一个当前端点快照
  useEffect(() => {
    if (!savedWaypoints || savedWaypoints.length === 0) return
    if (dataTyped.routeRef) return
    rf.setEdges((eds) =>
      eds.map((edge) => {
        if (edge.id !== id) return edge
        const d = (edge.data ?? {}) as EdgeData
        const wps = d.waypoints
        if (!wps || wps.length === 0 || d.routeRef) return edge
        return {
          ...edge,
          data: {
            ...(edge.data ?? {}),
            routeRef: endpointSnapshot,
          },
        }
      }),
    )
  }, [id, rf, savedWaypoints, dataTyped.routeRef, endpointSnapshot])

  // 拖拽某个线段（移动该线段两端的中间点）
  const handleSegmentDrag = useCallback(
    (segIndex: number, seg: { isVertical: boolean }) => (e: React.MouseEvent) => {
      e.stopPropagation()
      const startX = e.clientX
      const startY = e.clientY
      
      // IMPORTANT:
      // points may contain extra terminal-lead / autoOffset doglegs that are not persisted in data.waypoints.
      // Drag should operate on the rendered polyline and then re-normalize back to orthogonal waypoints.
      const basePoints: Point[] = points.map((p) => ({ ...p }))
      const n = basePoints.length

      const handleMove = (evt: MouseEvent) => {
        const cur = rf.screenToFlowPosition({ x: evt.clientX, y: evt.clientY })
        const start = rf.screenToFlowPosition({ x: startX, y: startY })
        const dx = snapToGrid(cur.x - start.x, EDGE_STEP_UNIT)
        const dy = snapToGrid(cur.y - start.y, EDGE_STEP_UNIT)
        
        const moved = basePoints.map((p) => ({ ...p }))
        const affect = [segIndex, segIndex + 1]
        for (const idx of affect) {
          if (idx <= 0 || idx >= n - 1) continue // never move endpoints
          if (seg.isVertical) moved[idx].x += dx
          else moved[idx].y += dy
        }
        
        const newWaypoints = moved.slice(1, -1)
        const anchorPref = resolveDragNormalizeAnchorPreference({
          movedPoints: moved,
          segIndex,
          isVertical: seg.isVertical,
          source: sourcePoint,
          target: targetPoint,
          sourcePosition: srcPos,
          targetPosition: tgtPos,
        })
        const normalized = normalizeOrthogonalWaypoints(sourcePoint, targetPoint, newWaypoints, srcPos, tgtPos, {
          anchor: anchorPref,
        })
        rf.setEdges((eds) =>
          eds.map((edge) =>
            edge.id === id
              ? {
                  ...edge,
                  data: {
                    ...(edge.data ?? {}),
                    waypoints: normalized,
                    routeRef: endpointSnapshot,
                  },
                }
              : edge,
          ),
        )
      }

      const handleUp = () => {
        window.removeEventListener('mousemove', handleMove)
        window.removeEventListener('mouseup', handleUp)
      }

      window.addEventListener('mousemove', handleMove)
      window.addEventListener('mouseup', handleUp)
    },
    [id, rf, points, sourcePoint, targetPoint, srcPos, tgtPos, endpointSnapshot],
  )

  const handleLabelDrag = useCallback(
    (e: React.MouseEvent) => {
      if (editing) return
      e.stopPropagation()
      const startX = e.clientX
      const startY = e.clientY
      const currentWaypoints: Point[] = effectiveWaypoints
        ? effectiveWaypoints.map((p) => ({ ...p }))
        : points.slice(1, -1).map((p: Point) => ({ ...p }))

      const handleMove = (evt: MouseEvent) => {
        const cur = rf.screenToFlowPosition({ x: evt.clientX, y: evt.clientY })
        const start = rf.screenToFlowPosition({ x: startX, y: startY })
        const dx = snapToGrid(cur.x - start.x, EDGE_STEP_UNIT)
        const dy = snapToGrid(cur.y - start.y, EDGE_STEP_UNIT)

        // 移动所有中间点
        const newWaypoints = currentWaypoints.map(wp => ({
          x: wp.x + dx,
          y: wp.y + dy,
        }))
        
        const normalized = normalizeOrthogonalWaypoints(sourcePoint, targetPoint, newWaypoints, srcPos, tgtPos)
        rf.setEdges((eds) =>
          eds.map((edge) =>
            edge.id === id
              ? {
                  ...edge,
                  data: {
                    ...(edge.data ?? {}),
                    waypoints: normalized,
                    routeRef: endpointSnapshot,
                  },
                }
              : edge,
          ),
        )
      }

      const handleUp = () => {
        window.removeEventListener('mousemove', handleMove)
        window.removeEventListener('mouseup', handleUp)
      }

      window.addEventListener('mousemove', handleMove)
      window.addEventListener('mouseup', handleUp)
    },
    [id, rf, editing, effectiveWaypoints, points, sourcePoint, targetPoint, srcPos, tgtPos, endpointSnapshot],
  )

  const commit = (next: string) => {
    const trimmed = next.trim()
    rf.setEdges((eds) =>
      eds.map((e) =>
        e.id === id
          ? {
              ...e,
              label: trimmed || undefined,
              data: { ...(e.data ?? {}), editingLabel: false },
            }
          : e,
      ),
    )
  }

  const markerKey =
    `${id}-${JSON.stringify(markerStart ?? null)}-${JSON.stringify(markerEnd ?? null)}`
  const markerWidth = 4
  const markerHeight = 8
  const markerRefX = 1.5
  const arrowStyle = dataTyped.arrowStyle ?? 'end'
  const hasReverseEdge = useMemo(
    () => allEdges.some((e) => (e as any).source === target && (e as any).target === source),
    [allEdges, source, target],
  )
  const hasStartArrow =
    arrowStyle === 'start' ||
    arrowStyle === 'both' ||
    (arrowStyle === 'end' && hasReverseEdge) ||
    (arrowStyle == null && Boolean(markerStart))
  const hasEndArrow = arrowStyle === 'end' || arrowStyle === 'both' || (arrowStyle == null && Boolean(markerEnd))
  const startKind = hasStartArrow ? markerKindFrom(markerStart) ?? 'closed' : null
  const endKind = hasEndArrow ? markerKindFrom(markerEnd) ?? 'closed' : null
  const startMarkerId = `${id}-start-marker`
  const endMarkerId = `${id}-end-marker`
  const startMarkerUrl = startKind ? `url(#${startMarkerId})` : undefined
  const endMarkerUrl = endKind ? `url(#${endMarkerId})` : undefined

  return (
    <>
      {(startKind || endKind) && (
        <defs>
          {startKind && (
            <marker
              id={startMarkerId}
              markerWidth={markerWidth}
              markerHeight={markerHeight}
              viewBox="0 0 10 10"
              preserveAspectRatio="none"
              refX={markerRefX}
              refY={5}
              orient="auto-start-reverse"
              markerUnits="userSpaceOnUse"
            >
              {startKind === 'closed' ? (
                <path
                  d="M 0 0 L 10 5 L 0 10 z"
                  fill={markerColorFrom(style, markerStart)}
                  stroke={markerColorFrom(style, markerStart)}
                  strokeWidth={0.35}
                  strokeLinejoin="round"
                />
              ) : (
                <path
                  d="M 0 0 L 10 5 L 0 10"
                  fill="none"
                  stroke={markerColorFrom(style, markerStart)}
                  strokeWidth={1.5}
                />
              )}
            </marker>
          )}
          {endKind && (
            <marker
              id={endMarkerId}
              markerWidth={markerWidth}
              markerHeight={markerHeight}
              viewBox="0 0 10 10"
              preserveAspectRatio="none"
              refX={markerRefX}
              refY={5}
              orient="auto"
              markerUnits="userSpaceOnUse"
            >
              {endKind === 'closed' ? (
                <path
                  d="M 0 0 L 10 5 L 0 10 z"
                  fill={markerColorFrom(style, markerEnd)}
                  stroke={markerColorFrom(style, markerEnd)}
                  strokeWidth={0.35}
                  strokeLinejoin="round"
                />
              ) : (
                <path
                  d="M 0 0 L 10 5 L 0 10"
                  fill="none"
                  stroke={markerColorFrom(style, markerEnd)}
                  strokeWidth={1.5}
                />
              )}
            </marker>
          )}
        </defs>
      )}
      <BaseEdge
        key={markerKey}
        id={id}
        path={edgePath}
        markerStart={startMarkerUrl}
        markerEnd={endMarkerUrl}
        style={{ ...style, ...semanticStyle } as any}
        interactionWidth={interactionWidth ?? 24}
      />

      {/* 每个线段的拖拽区域 */}
      {segments.map((seg, idx) => {
        // 2 段（L 型）也允许拖拽；>=3 段时仅开放中间段，避免误拖端口短边。
        if (segments.length < 2) return null
        const twoSegmentPath = segments.length === 2
        if (!twoSegmentPath && (idx === 0 || idx === segments.length - 1)) return null
        
        const segLength = seg.length
        
        const isHovered = hoveredSegment === idx
        
        return (
          <EdgeLabelRenderer key={`seg-${idx}`}>
            <div
              style={{
                position: 'absolute',
                transform: `translate(-50%, -50%) translate(${seg.midX}px, ${seg.midY}px)`,
                width: seg.isVertical ? 16 : Math.max(segLength - 24, 24),
                height: seg.isVertical ? Math.max(segLength - 24, 24) : 16,
                cursor: seg.isVertical ? 'ew-resize' : 'ns-resize',
                pointerEvents: 'all',
                background: (selected || isHovered) ? 'rgba(59, 130, 246, 0.2)' : 'transparent',
                borderRadius: 12,
                transition: 'background 0.15s',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
              onMouseEnter={() => setHoveredSegment(idx)}
              onMouseLeave={() => setHoveredSegment(null)}
              onMouseDown={handleSegmentDrag(idx, seg)}
            >
              {(selected || isHovered) && (
                <div
                  style={{
                    width: seg.isVertical ? 4 : 24,
                    height: seg.isVertical ? 24 : 4,
                    background: '#3b82f6',
                    borderRadius: 12,
                    opacity: 0.8,
                  }}
                />
              )}
            </div>
          </EdgeLabelRenderer>
        )
      })}

      <SmartEdgeLabel
        edgeId={id}
        anchors={anchors}
        labelLayout={dataTyped.labelLayout}
        labelStyle={labelStyleObj}
        text={typeof label === 'string' ? label : ''}
        editing={editing}
        textOnly={Boolean(dataTyped.semanticType) || Boolean(dataTyped.labelTextOnly)}
        onPointerDown={handleLabelDrag}
        onDoubleClick={(e) => {
          e.stopPropagation()
          if (!editing) {
            rf.setEdges((eds) =>
              eds.map((edge) =>
                edge.id === id
                  ? { ...edge, data: { ...(edge.data ?? {}), editingLabel: true, labelSettingsUnlocked: true } }
                  : { ...edge, data: { ...(edge.data ?? {}), editingLabel: false } },
              ),
            )
          }
        }}
        editChildren={
          <>
            <QuickTextStyleToolbar
                anchorRef={inputRef}
                visible={editing}
                onRequestClose={() => {
                  const el = inputRef.current
                  commit(el ? el.value : (label as string) ?? '')
                }}
                fontSize={labelFontSize}
                fontWeight={labelFontWeight}
                onFontSizeChange={(v) => {
                  const next: EdgeLabelStyle = {
                    ...labelStyleObj,
                    fontSize: v,
                    fontWeight: labelFontWeight,
                    color: labelColor,
                  }
                  rf.setEdges((eds) =>
                    eds.map((e) =>
                      e.id === id
                        ? {
                            ...e,
                            labelStyle: next,
                            data: { ...(e.data ?? {}), labelStyle: next },
                          }
                        : e,
                    ),
                  )
                }}
                onFontWeightChange={(v) => {
                  const next: EdgeLabelStyle = {
                    ...labelStyleObj,
                    fontSize: labelFontSize,
                    fontWeight: v,
                    color: labelColor,
                  }
                  rf.setEdges((eds) =>
                    eds.map((e) =>
                      e.id === id
                        ? {
                            ...e,
                            labelStyle: next,
                            data: { ...(e.data ?? {}), labelStyle: next },
                          }
                        : e,
                    ),
                  )
                }}
                textColor={labelColor}
                onTextColorChange={(v) => {
                  const next: EdgeLabelStyle = {
                    ...labelStyleObj,
                    fontSize: labelFontSize,
                    fontWeight: labelFontWeight,
                    color: v,
                  }
                  rf.setEdges((eds) =>
                    eds.map((e) =>
                      e.id === id
                        ? {
                            ...e,
                            labelStyle: next,
                            data: { ...(e.data ?? {}), labelStyle: next },
                          }
                        : e,
                    ),
                  )
                }}
              />
              <textarea
                ref={inputRef}
                autoFocus
                defaultValue={(label as string) ?? ''}
                rows={1}
                style={{
                  fontSize: labelFontSize,
                  fontWeight: labelFontWeight,
                  color: labelColor,
                  padding: '2px 4px',
                  borderRadius: 12,
                  border: '1px solid #e5e7eb',
                  background: '#ffffff',
                  minWidth: 60,
                  resize: 'none',
                  fontFamily: 'inherit',
                  height: 'auto',
                  overflow: 'hidden',
                }}
                onChange={(e) => {
                  e.target.style.height = 'auto'
                  e.target.style.height = e.target.scrollHeight + 'px'
                }}
                onBlur={(e) => {
                  if ((e.relatedTarget as HTMLElement)?.closest?.(`[${QUICK_TOOLBAR_DATA_ATTR}]`)) return
                  commit(e.target.value)
                }}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && (e.shiftKey || e.metaKey || e.ctrlKey)) {
                    e.preventDefault()
                    commit((e.target as HTMLTextAreaElement).value)
                  }
                  if (e.key === 'Escape') {
                    e.preventDefault()
                    rf.setEdges((eds) =>
                      eds.map((edge) =>
                        edge.id === id
                          ? { ...edge, data: { ...(edge.data ?? {}), editingLabel: false } }
                          : edge,
                      ),
                    )
                  }
                }}
              />
          </>
        }
      />
    </>
  )
}
